name: Build

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        dotnet: [6.0.408]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Build
      run: dotnet run build
    - name: Run tests
      run: dotnet run test
