name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: Build library and run unit tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Build library
      run: ./build.sh
    - name: Run tests
      run: dotnet test -s test.runsettings -r TestResults
    - name: Upload coverage report
      run: |
        curl -s https://codecov.io/bash > codecov
        chmod +x codecov
        ./codecov -f "TestResults/*/coverage.opencover.xml" -t ${{ secrets.codecovtoken }}
